# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: dev
  username: brian
  password: Steelers7
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: test
  username: brian
  password: Steelers7
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: prod
  username: entrobe
  password: Steelers7
